### ISSUE TITLE
Using Pokemon Center crashes the game

### ISSUE THREAD

**Issue by Ziko577** [roukaour/polishedcrystal#110]
I played the current beta release using the No-RTC patch and the moment I went to heal my starter pokemon, the game just crashed. No idea why it happened but it did. It brings a text box up and then freezes.

![img_20170725_203207 1](https://user-images.githubusercontent.com/6496151/28599445-9fa50042-7178-11e7-965e-bb63ced6ed19.jpg)

**Comment by roukaour** [comment]
What emulator is this? Make sure you apply the patch to an original Crystal 1.0 (UE) ROM. I cannot reproduce this problem with the no-RTC build in VBA or BGB.

**Comment by Ziko577** [comment]
It's Gameyob on my DS. I did use an 1.0 UE ROM. Perhaps it could've been a bad rom. I'll try again shortly and report back.
