### ISSUE TITLE
No-RTC clock gets stuck in a loop

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#113]
If you start a game at Sunday 20:00 and let time pass, it will reach Monday 19:59 correctly, but then loops back to Sunday 20:00 instead of Monday 20:00.

![image](https://user-images.githubusercontent.com/1761576/28895122-24ae4244-77a5-11e7-973f-f4d38ba78e82.png)

Edit: Reset the clock by pressing Down+B at the title screen. Sunday 0:00 turns into Saturday at 0:30. Thursday 10:07 turns into Wednesday at 10:30.

**Comment by roukaour** [comment]
@Kroc , can you please take a look at this? The cause is probably in home/game_time.asm.

**Comment by Kroc** [comment]
Could be my RTC overflow roll-over code triggering early. I'll try get this sorted this week.

**Comment by Kroc** [comment]
I've been looking into this and I feel that my original patch was based on very limited understanding of the code so I've been going through and documenting the actual behaviour of the various bits of time code so I hope to have a comprehensive solution as soon as I can. keep up the amazing work you're doing on this project.

**Comment by roukaour** [comment]
Sounds great, @Kroc !

**Comment by Kroc** [comment]
I've found the fix for this particular issue, but now I understand the RTC behaviour better I can see why my overflow code is all wrong. I'll create a pull request when I've got a good-looking patch ready.
