### ISSUE TITLE
Route 34 Breeder Julie always battle-able in 3.0.0 beta

### ISSUE THREAD

**Issue by Linuxuser437442** [roukaour/polishedcrystal#117]
On route 34 Breeder Julie is always battle-able. When ever you leave route 34 and then come back, you can battle her again, and again, and again. Does the whole Exclamation thing and everything. 

Platform: Android 7.0, Nexus 6p
Emulator: John GBC

**Comment by roukaour** [comment]
All Breeders are rebattlable, like in Gen 5.
