### ISSUE TITLE
Some NPC trainers use wrong items

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#12]
Lance uses X Spcl. Atk, Karen uses Potion, etc. (This was in 2.2.0.)

**Comment by FredrIQ** [comment]
I had Lance use a Potion on me when testing his new team, so this is still an issue.

**Comment by FredrIQ** [comment]
Turns out this was a bug originating in Crystal. Fixed in 8ab4192c8fcd9dd4e1582d0b44cec037f4304ff2.
