### ISSUE TITLE
Item names are printed incorrectly in battle

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#125]
Knock Off and Thief both print garbage instead of item names.

![image](https://user-images.githubusercontent.com/1761576/29375426-f4345958-8282-11e7-93e0-f166a158fffb.png)

![image](https://user-images.githubusercontent.com/1761576/29375433-faf17b90-8282-11e7-8f7d-4b676079b51a.png)

**Comment by FredrIQ** [comment]
Fixed Knock Off. Can't reproduce the Thief issue.
