### ISSUE TITLE
Some abilities incorrectly activate when the foe is KO'ed

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#126]
Abilities like Cute Charm can activate even when the foe has been knocked out and the activation effect is pointless.

![image](https://user-images.githubusercontent.com/1761576/29490997-e3eb2b1c-851b-11e7-9dd0-4d6d11f4b604.png)

**Comment by FredrIQ** [comment]
Fixed in 33b47c2e950e458606979140a4353634f1097c31.
