### ISSUE TITLE
Wonder Trade Unown looks corrupt before Ruins of Alph unlock

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#136]
Even before making them appear in the Ruins of Alph, Unown is available via Wonder Trade. It then has a corrupt sprite:

![image](https://user-images.githubusercontent.com/1761576/30552011-8fea87f4-9c6a-11e7-89eb-f0c47afbf2c4.png)

**Comment by Acrozz** [comment]
I think that Unown shouldn't be obtainable via Wonder Trade (what happens if you get various forms via Wonder Trade and then enter Ruins of Alph for the first time? Do you get the UnownDex like normal?)

**Comment by roukaour** [comment]
Yes, that was my planned solution. (Although I thought it was already implemented...)
