### ISSUE TITLE
totally fucked up overworld sprite

### ISSUE THREAD

**Issue by ruvaldak** [roukaour/polishedcrystal#146]
each movement frame thingy goes from rattata to raticate and such.

latest commit

**Comment by ruvaldak** [comment]
fixes itself temporarily when you open the menu

**Comment by roukaour** [comment]
Check out engine/overworld.asm. Now that Violet Outskirts connects the already-hugely-interconnected New Bark+Cherrygrove+Violet area to the Mahogany area, the whole place needs more sprites than will fit in VRAM. I need to make some sacrifices to limit the NPC variety.
