### ISSUE TITLE
Talking to an NPC for rematch, does not show their name

### ISSUE THREAD

**Issue by Kroc** [roukaour/polishedcrystal#147]
I.e., Joey phones you for a rematch; when you speak to Joey it says "I've been waiting", but does not prefix this with his name as it does in other conversations. It would be nice to know who you're talking to as regards to why you've triggered a battle.

Suggestion for 4.0: NPC Portraits?

**Comment by roukaour** [comment]
There are no Gen 2 conversations which prefix the trainer's name. And you know who you're talking to because presumably you just came there to battle.
