### ISSUE TITLE
Suggestion: Trainer rematch improvements

### ISSUE THREAD

**Issue by Kroc** [roukaour/polishedcrystal#148]
This is a Quality-Of-Life suggestion: When a Trainer phones you for a rematch, it can be difficult to locate them, especially when you're far in the game or haven't played for a while. Suggestions:

1. Display a blinking phone icon, or some such indicator above the NPC in the overworld, so it is clear that the Trainer is available for a rematch.

2. After a Trainer phone call, If the player has Fly available, perhaps pop up a menu to say "Fly to xxx now?", allowing you to go straight to the fight there and then.

**Comment by roukaour** [comment]
Unfortunately it's hard enough to fit NPC sprites alone into VRAM; blinking rematch icons would be impossible. (Note that when you Fly, everyone disappears to make room for the swirling leaves.)

**Comment by Kroc** [comment]
Could you not use the mobile phone tile from the font? (like when you receive a phone call), it wouldn't have to be a sprite if the NPC is not moving, you could blink an on-screen map tile.

**Comment by roukaour** [comment]
It would still have to be an OAM object, not a background tile, and that's the VRAM I'm talking about being full. Not to mention, the obvious way to implement it would be with a new person_event, and maps have a limit on those too.

**Comment by Kroc** [comment]
I was playing last night and I realised that when a Trainer first spots you, the exclamation mark bubble appears over their head; how is that handled? You could blink that on and off, and/or replace the exclamation mark symbol with the phone symbol.
