### ISSUE TITLE
Giving Items to Pokemon should default to the Berries Pocket

### ISSUE THREAD

**Issue by Kroc** [roukaour/polishedcrystal#149]
Selecting a Pokemon and choosing "Item > Give" from the menu does not go to the Berries Pocket (where it would be most useful) by default.

**Comment by roukaour** [comment]
Held items in the Items pocket are at least as useful; and this would violate the [principal of least surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment), since people expect it to open to the last used pocket.
