### ISSUE TITLE
AI doesn't Struggle

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#157]
Instead it just uses its 0 PP move.

![image](https://i.imgur.com/58Gg8CV.gif)

This problem also occurs with Disabled moves.

![image](https://user-images.githubusercontent.com/1761576/34184236-9ea81304-e4ec-11e7-8f7e-14ed4c690dce.png)

The opposite can also happen: "A Swimmer in Cerulean Cape has 2 Cloyster and a Dewgong. The Dewgong is confirmed to have Take Down, but it occasionally uses Struggle, even though it has PP available for Take Down..."

**Comment by FredrIQ** [comment]
Might be fixed by eef21c737e0c6cbd99e9a4c42d791de8b0c0458a.

**Comment by roukaour** [comment]
Yes, it appears to be fixed.
