### ISSUE TITLE
Fix overflow in UpdateNoRTC for NO_RTC build

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#25]
> What I need to do here is mask off the top bits and check if the current hi-days is %11111 (i.e. just before it would overflow). When that happens there's a few possibilities here:
> 
> * Reset the whole RTC to zero
> * Go back a week (so the last week repeats itself indefinitely)
> * Repeat the last day indefinitely
> 
> NOTE: 13 bits for days allows for 8'192 in-game days -- over 22 in-game years -- which, given that a day in-game takes 4 real hours, would require the player to play for 3.75 continuous real years to overflow.

**Comment by Kroc** [comment]
Working on this, but testing it is proving horrendous.

**Comment by roukaour** [comment]
I assume you've already edited the New Game routine to initialize hi-days to %11110, or something like that so you can test more quickly?

**Comment by Kroc** [comment]
Just having issues with the development environment. It's painful and slow to iterate, also now I'm looking and testing the code in detail I'm noticing a number of bugs. I'll push a patch once I'm confident that it's accurate and reliable.
