### ISSUE TITLE
Redundant code in LoadEnemyMon and InitEnemyMon

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#3]
battle/core.asm's LoadEnemyMon jumps early to InitEnemyMon if it's a link or Battle Tower battle, but continues with its own code for regular trainer battles. InitEnemyMon simply reads everything from the OTPartyMon data structure. LoadEnemyMon apparently has a more complicated way of doing the same thing, with lots of individual checks for "if it's a trainer battle, get this particular data item from OTPartyMon, otherwise generate a new one for a wild Pokémon". The only thing that isn't redundant is that LoadEnemyMon registers Pokémon as seen in the Pokédex.

**Comment by FredrIQ** [comment]
This is done now.
