### ISSUE TITLE
Slight Compilation error

### ISSUE THREAD

**Issue by MadoKage** [roukaour/polishedcrystal#31]
Make Debug doesn't seem to do anything while Make Crystal does this error

error: Section name "Audio" is already in use

**Comment by roukaour** [comment]
Check out the latest commit. "make crystal", "make faithful", and "make debug" all work for me, and SECTION "Audio" was renamed to SECTION "WRAM Audio" a while ago.

**Comment by MadoKage** [comment]
odd since doing "make debug" does

make: *** No rule to make target 'debug'.  Stop.

never encounter this before also I'm still getting the audio error, should I rename a file?

**Comment by roukaour** [comment]
Check out the latest commit. There is definitely a target 'debug' defined in the [Makefile](https://github.com/roukaour/polishedcrystal/blob/master/Makefile#L57).

**Comment by MadoKage** [comment]
all the other ones works its just "debug" that still says it, not sure what the issue is

even if I still try to make them it still does the audio section error

**Comment by MadoKage** [comment]
If this is annoying you about this particular issue, I apologize

**Comment by MadoKage** [comment]
OH wow I see the problem, I didn't realize you rename your git link to pokecrystal to polishedcrystal

way too used to using the old link, my mistake
