### ISSUE TITLE
Foe's Substitute makes your moves become something else

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#7]
After rematch Koga's Tentacruel used Substitute, my Mewtwo's moves all turn into Ember. Switching out does not fix this.

Against a wild level 2 Pidgey hacked to know Substitute, my moves now become Double Slap. Against a level 3, Aerial Ace.

**Comment by FredrIQ** [comment]
To clarify on what happens: move index uses the opponent's level for whatever reason

**Comment by roukaour** [comment]
The value is corrupted at some point before MoveSelectionScreen returns, since replacing its return code:

    .skip2
    	ld [CurPlayerMove], a
    	xor a
    	ret

with this:

    .skip2
    	ld a, SWORDS_DANCE
    	ld [CurPlayerMove], a
    	xor a
    	ret

makes the player always use Swords Dance even after an enemy Substitute.
