### ISSUE TITLE
AI use of CheckTypeMatchup is completely broken

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#8]
@FredrIQ:

> The code assumes something that is incorrect, completely breaking its usage of this function in every case it is used (which is pretty much everywhere in its switch-out routines, and various move scoring checks). I assumed this was introduced by my changes to said routine, but the bug is actually present in vanilla Crystal. Found it while trying to implement Anticipation.
> Fixing this will be rather annoying.

> Basically, whenever it uses CheckTypeMatchup (not BattleCheckTypeMatchup), it assumes that it can make the function do the right thing by setting hl to the defending types (hl+1 for type 2), which is correct, and a to the attacking type which isn't correct, because CheckTypeMatchup will proceed to get the type from the current move struct by "ld a, BATTLE_VARS_MOVE_TYPE; call GetBattleVar". I assumed this was a change I did myself, but looking at pret shows that it is there in vanilla as well. It is, however, more annoying to fix in Polished Crystal, since not only does one have to properly handle offensive/defensive types, but also abilities (just ignoring them is a bad idea unless one wants to make the AI not understand abilities).
> Earlier tonight I was going to fix this by making CheckTypeMatchup all read from hl/a/b/c/d instead of reading the battle state on the fly such as:
> hl is defending type (hl+1 the secondary one)
> a is the offensive move
> b is the offensive ability
> c is the defending ability
> d is 0 or 1 depending on identification (and set to 1 by CheckTypeMatchup regardless, if b is SCRAPPY.
> However the result became quite awkward since I pretty much run out of usable registers and I was afraid to introduce bugs. Not sure what to do about this. Possibly do another attempt relying on RAM buffers (stuff like Buffer1-6, etc) so I don't have to do a ton of push/popping to do what I want.

> Nope, hence the comment is still there. This isn't related to type matchups being broken in general (which was recently fixed), but a vanilla AI bug that completely broke switch logic.
> Fixing this is a trivial change in vanilla Crystal, but due to the fact that type matchup logic has to factor in abilities, is a much harder change to apply properly to Polished Crystal (unless you decide to simply just ignore abilities, which I don't want to). The reason is that the cases where the AI use of this is broken is the case where the AI is checking non-active Pokémon. This means that not only is the type not matching (something the AI handles, it just misunderstands what the function does in a trivial way but completely broken way), but also defending and attacking Pokémon's abilities.
> There are 2 methods for how to go about fixing it.
> 1: Whenever the AI wants to check this, temporarily change both attacking and defending Pokémon's ability. This needs to change back (properly! Keep Trace in mind, never mind Transform/Imposter) afterwards
> 2: Set ability to check in some parameter for the CheckTypeMatchup function. This is problematic because it kills any ability to reuse general ability logic (stuff like Mold Breaker, etc) and also needs free RAM (because there isn't enough registers) -- allthough I think Buffer* would do here.
> There is also an edge case issue involving powder moves and Grass types, but I think this doesn't come up in practice because they're all status moves.
> At this point I've concluded that messing with this isn't worthwhile considering that I want to rewrite the AI either way at some point later.

**Comment by FredrIQ** [comment]
Fixed after AI switch logic rewrite
