### ISSUE TITLE
Caught Pokémon have wrong held items

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#9]
I've caught a Teddiursa holding an Ultra Ball and a Caterpie (IIRC) holding a Great Ball. On the other hand, a Bellsprout I caught had the correct Gold Leaf.

[Shlotz](https://www.pokecommunity.com/showthread.php?p=9613745#post9613745) has caught an Ekans holding a Safari Ball, and another holding a Master Ball.

Edit: Adrevilicious on Discord confirmed that this is still an issue, with Spinarak holding a Safari Ball.

**Comment by FredrIQ** [comment]
There was at least one bug going on here -- Wrap and other trapping moves would replace the user's held item with Master Ball or Safari Ball at random (if it was 4 or 5 turns), and in theory Lure Ball if 7 turns (if it could hold a Grip Claw). This explains the Ekans case, but not the Teddiursa/Caterpie case.

**Comment by roukaour** [comment]
The Wrap bug also explains the Spinarak case. Teddiursa and Caterpie were observed long enough ago that the original issue might be resolved.

**Comment by FredrIQ** [comment]
Relabeling this then

**Comment by FredrIQ** [comment]
Testers would have noticed by now, closing unless someone encounters issues again.
