### ISSUE TITLE
Life Orb does not subtract HP if you KO the enemy

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#94]
Reminiscent of the Gen 1 Hyper Beam glitch where it wouldn't recharge after a KO.

**Comment by FredrIQ** [comment]
Oh right, I forgot that PostHitEffects doesn't run if you faint the enemy...

Similar issues with Shell Bell, Rocky Helmet, and other stuff in that function then.

**Comment by FredrIQ** [comment]
Fixed in ff0a391b0517f249cf8eca417039277605c7badf.
