### ISSUE TITLE
Unown changes form when caught

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#96]
(Edit: this happens to all caught Pokémon, not just ones with variant forms. Possibly their stats are being re-randomly generated on capture.)

![image](https://user-images.githubusercontent.com/1761576/27901120-d34c439e-61fe-11e7-9dd9-761f6533cb9a.png)

Here a Unown D becomes B:

![image](https://user-images.githubusercontent.com/1761576/27890699-71b09716-61c2-11e7-81bd-2ce528d67fc0.png)

![image](https://user-images.githubusercontent.com/1761576/27890701-73ff5dfe-61c2-11e7-9429-910c4200e7f9.png)

![image](https://user-images.githubusercontent.com/1761576/27890702-764168be-61c2-11e7-87fe-494951b01cb4.png)

This is serious because it prevents, or at least hinders, completion of the Unown Dex and unlocking certain areas.

Edit: I caught some more.

* I → J
* G → B
* E → I
* G → I
* C → E
* H → G
* G → G

It's not consistent, and may be related to recalculating stats, given that their HP was corrupted:

![image](https://user-images.githubusercontent.com/1761576/27890817-308557f8-61c3-11e7-8903-0a5978922845.png)

Edit: This affects Magikarp forms as well.

**Comment by FredrIQ** [comment]
Should be fixed now, but I don't have a save handy at the place.
