### ISSUE TITLE
Burn does not halve Attack

### ISSUE THREAD

**Issue by roukaour** [roukaour/polishedcrystal#97]
Equalsign: "When Totodile isn't burned it deals 5 damage to my cyndaquil using scratch, but even when is burned by Flame Body it continues to deal 5 damage as it was before."

![image](https://user-images.githubusercontent.com/1761576/27890861-98395160-61c3-11e7-9ee0-246b425b0935.png)

**Comment by FredrIQ** [comment]
Totodile has Guts. With that said, if Guts was in play it should've dealt 10 damage.

**Comment by FredrIQ** [comment]
Fixed in bb2f83c3fa5f30c89c8061aea7e3a057873fda90.
